#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server to display "Hello World!" at the root URL

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Change file ownership
sudo chown -R ubuntu /var/www

# Create an HTML file that contains "Hello World!"
echo 'Hello World!' > /var/www/html/index.html

# Restart Nginx without using systemctl
sudo service nginx restart

