#!/usr/bin/env bash
# This script installs Nginx and configures a 301 redirection from /redirect_me to another URL

# Update package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Configure Nginx to redirect /redirect_me to another page
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx without using systemctl
service nginx restart

