#!/usr/bin/env bash
# This script installs and configures HAproxy to distribute traffic to web-01 and web-02 using a roundrobin algorithm.

# Update package lists and install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 81376-web-01 35.153.57.10:80 check
    server 81376-web-02 YOUR_WEB_02_IP:80 check
EOL

# Enable and start HAproxy service
sudo systemctl enable haproxy
sudo systemctl restart haproxy
