#!/usr/bin/env bash
# This script installs Apache, creates a webpage, and starts the Apache server

apt-get update
apt-get install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
